-module(uaparser_browser).

%% API
-export([browsers/0]).

browsers() ->
    [{[{<<"family">>,<<"outlook">>},
        {<<"name">>,<<"outlook">>},
        {<<"manufacturer">>,<<"microsoft">>},
        {<<"browser_type">>,<<"email_client">>},
        {<<"rendering_engine">>,<<"word">>},
        {<<"version_regex">>,<<"msoffice (([0-9]+))">>},
        {<<"aliases">>,[<<"msoffice">>]},
        {<<"children">>,
            [{[{<<"family">>,<<"outlook">>},
                {<<"name">>,<<"outlook 2007">>},
                {<<"manufacturer">>,<<"microsoft">>},
                {<<"browser_type">>,<<"email_client">>},
                {<<"rendering_engine">>,<<"word">>},
                {<<"aliases">>,[<<"msoffice 12">>]},
                {<<"children">>,[]}]},
                {[{<<"family">>,<<"outlook">>},
                    {<<"name">>,<<"outlook 2013">>},
                    {<<"manufacturer">>,<<"microsoft">>},
                    {<<"browser_type">>,<<"email_client">>},
                    {<<"rendering_engine">>,<<"word">>},
                    {<<"aliases">>,[<<"microsoft outlook 15">>]},
                    {<<"children">>,[]}]},
                {[{<<"family">>,<<"outlook">>},
                    {<<"name">>,<<"outlook 2010">>},
                    {<<"manufacturer">>,<<"microsoft">>},
                    {<<"browser_type">>,<<"email_client">>},
                    {<<"rendering_engine">>,<<"word">>},
                    {<<"aliases">>,[<<"msoffice 14">>,<<"microsoft outlook 14">>]},
                    {<<"children">>,[]}]}]}]},
        {[{<<"family">>,<<"ie">>},
            {<<"name">>,<<"internet explorer">>},
            {<<"manufacturer">>,<<"microsoft">>},
            {<<"browser_type">>,<<"web_browser">>},
            {<<"rendering_engine">>,<<"trident">>},
            {<<"version_regex">>,<<"msie (([\\d]+)\\.([\\w]+))">>},
            {<<"aliases">>,[<<"msie">>,<<"trident">>,<<"ie ">>]},
            {<<"children">>,
                [{[{<<"family">>,<<"ie">>},
                    {<<"name">>,<<"windows live mail">>},
                    {<<"manufacturer">>,<<"microsoft">>},
                    {<<"browser_type">>,<<"email_client">>},
                    {<<"rendering_engine">>,<<"trident">>},
                    {<<"aliases">>,[<<"outlook-express/7.0">>]},
                    {<<"children">>,[]}]},
                    {[{<<"family">>,<<"ie">>},
                        {<<"name">>,<<"ie mobile 11">>},
                        {<<"manufacturer">>,<<"microsoft">>},
                        {<<"browser_type">>,<<"mobile_browser">>},
                        {<<"rendering_engine">>,<<"trident">>},
                        {<<"aliases">>,[<<"iemobile/11">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"ie">>},
                        {<<"name">>,<<"ie mobile 10">>},
                        {<<"manufacturer">>,<<"microsoft">>},
                        {<<"browser_type">>,<<"mobile_browser">>},
                        {<<"rendering_engine">>,<<"trident">>},
                        {<<"aliases">>,[<<"iemobile/10">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"ie">>},
                        {<<"name">>,<<"ie mobile 9">>},
                        {<<"manufacturer">>,<<"microsoft">>},
                        {<<"browser_type">>,<<"mobile_browser">>},
                        {<<"rendering_engine">>,<<"trident">>},
                        {<<"aliases">>,[<<"iemobile/9">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"ie">>},
                        {<<"name">>,<<"ie mobile 7">>},
                        {<<"manufacturer">>,<<"microsoft">>},
                        {<<"browser_type">>,<<"mobile_browser">>},
                        {<<"rendering_engine">>,<<"trident">>},
                        {<<"aliases">>,[<<"iemobile 7">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"ie">>},
                        {<<"name">>,<<"ie mobile 6">>},
                        {<<"manufacturer">>,<<"microsoft">>},
                        {<<"browser_type">>,<<"mobile_browser">>},
                        {<<"rendering_engine">>,<<"trident">>},
                        {<<"aliases">>,[<<"iemobile 6">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"ie">>},
                        {<<"name">>,<<"internet explorer 11">>},
                        {<<"manufacturer">>,<<"microsoft">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"trident">>},
                        {<<"version_regex">>,
                            <<"(?:trident\\/7|ie)(?:\\.[0-9]*;)?(?:.*rv:| )(([0-9]+)\\.?([0-9]+))">>},
                        {<<"aliases">>,[<<"trident/7">>,<<"ie 11.">>]},
                        {<<"exclusions">>,[<<"msie 7">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"ie">>},
                        {<<"name">>,<<"internet explorer 10">>},
                        {<<"manufacturer">>,<<"microsoft">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"trident">>},
                        {<<"aliases">>,[<<"msie 10">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"ie">>},
                        {<<"name">>,<<"internet explorer 9">>},
                        {<<"manufacturer">>,<<"microsoft">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"trident">>},
                        {<<"aliases">>,[<<"msie 9">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"ie">>},
                        {<<"name">>,<<"internet explorer 8">>},
                        {<<"manufacturer">>,<<"microsoft">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"trident">>},
                        {<<"aliases">>,[<<"msie 8">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"ie">>},
                        {<<"name">>,<<"internet explorer 7">>},
                        {<<"manufacturer">>,<<"microsoft">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"trident">>},
                        {<<"aliases">>,[<<"msie 7">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"ie">>},
                        {<<"name">>,<<"internet explorer 6">>},
                        {<<"manufacturer">>,<<"microsoft">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"trident">>},
                        {<<"aliases">>,[<<"msie 6">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"ie">>},
                        {<<"name">>,<<"internet explorer 5.5">>},
                        {<<"manufacturer">>,<<"microsoft">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"trident">>},
                        {<<"aliases">>,[<<"msie 5.5">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"ie">>},
                        {<<"name">>,<<"internet explorer 5">>},
                        {<<"manufacturer">>,<<"microsoft">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"trident">>},
                        {<<"aliases">>,[<<"msie 5">>]},
                        {<<"children">>,[]}]}]}]},
        {[{<<"family">>,<<"chrome">>},
            {<<"name">>,<<"chrome">>},
            {<<"manufacturer">>,<<"google">>},
            {<<"browser_type">>,<<"web_browser">>},
            {<<"rendering_engine">>,<<"webkit">>},
            {<<"version_regex">>,
                <<"chrome\\/(([0-9]+)\\.?([\\w]+)?(\\.[\\w]+)?(\\.[\\w]+)?)">>},
            {<<"aliases">>,[<<"chrome">>,<<"crmo">>,<<"crios">>]},
            {<<"exclusions">>,[<<"opr/">>,<<"web preview">>]},
            {<<"children">>,
                [{[{<<"family">>,<<"chrome">>},
                    {<<"name">>,<<"chrome mobile">>},
                    {<<"manufacturer">>,<<"google">>},
                    {<<"browser_type">>,<<"mobile_browser">>},
                    {<<"rendering_engine">>,<<"webkit">>},
                    {<<"version_regex">>,
                        <<"(?:crios|crmo|chrome)\\/(([0-9]+)\\.?([\\w]+)?(\\.[\\w]+)?(\\.[\\w]+)?)">>},
                    {<<"aliases">>,[<<"crmo">>,<<"crios">>,<<"mobile safari">>]},
                    {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 33">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/33">>]},
                        {<<"exclusions">>,[<<"opr/">>,<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 32">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/32">>]},
                        {<<"exclusions">>,[<<"opr/">>,<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 31">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/31">>]},
                        {<<"exclusions">>,[<<"opr/">>,<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 30">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/30">>]},
                        {<<"exclusions">>,[<<"opr/">>,<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 29">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/29">>]},
                        {<<"exclusions">>,[<<"opr/">>,<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 28">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/28">>]},
                        {<<"exclusions">>,[<<"opr/">>,<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 27">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/27">>]},
                        {<<"exclusions">>,[<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 26">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/26">>]},
                        {<<"exclusions">>,[<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 25">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/25">>]},
                        {<<"exclusions">>,[<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 24">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/24">>]},
                        {<<"exclusions">>,[<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 23">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/23">>]},
                        {<<"exclusions">>,[<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 22">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/22">>]},
                        {<<"exclusions">>,[<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 21">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/21">>]},
                        {<<"exclusions">>,[<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 20">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/20">>]},
                        {<<"exclusions">>,[<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 19">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/19">>]},
                        {<<"exclusions">>,[<<"web preview">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 18">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/18">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 17">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/17">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 16">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/16">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 15">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/15">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 14">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/14">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 13">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/13">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 12">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/12">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 11">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/11">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 10">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/10">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 9">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/9">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"chrome">>},
                        {<<"name">>,<<"chrome 8">>},
                        {<<"manufacturer">>,<<"google">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"chrome/8">>]},
                        {<<"children">>,[]}]}]}]},
        {[{<<"family">>,<<"omniweb">>},
            {<<"name">>,<<"omniweb">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"web_browser">>},
            {<<"rendering_engine">>,<<"webkit">>},
            {<<"aliases">>,[<<"omniweb">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"safari">>},
            {<<"name">>,<<"safari">>},
            {<<"manufacturer">>,<<"apple">>},
            {<<"browser_type">>,<<"web_browser">>},
            {<<"rendering_engine">>,<<"webkit">>},
            {<<"version_regex">>,<<"version\\/(([0-9]+)\\.?([\\w]+)?(\\.[\\w]+)?)">>},
            {<<"aliases">>,[<<"safari">>]},
            {<<"exclusions">>,[<<"opr/">>,<<"web preview">>,<<"googlebot-mobile">>]},
            {<<"children">>,
                [{[{<<"family">>,<<"safari">>},
                    {<<"name">>,<<"blackberry">>},
                    {<<"manufacturer">>,<<"blackberry">>},
                    {<<"browser_type">>,<<"mobile_browser">>},
                    {<<"rendering_engine">>,<<"webkit">>},
                    {<<"aliases">>,[<<"bb10">>]},
                    {<<"children">>,[]}]},
                    {[{<<"family">>,<<"safari">>},
                        {<<"name">>,<<"mobile safari">>},
                        {<<"manufacturer">>,<<"apple">>},
                        {<<"browser_type">>,<<"mobile_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"mobile safari">>,<<"mobile/">>]},
                        {<<"exclusions">>,[<<"googlebot-mobile">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"safari">>},
                        {<<"name">>,<<"silk">>},
                        {<<"manufacturer">>,<<"amazon">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"version_regex">>,
                            <<"silk\\/(([0-9]+)\\.?([\\w]+)?(\\.[\\w]+)?(\\-[\\w]+)?)">>},
                        {<<"aliases">>,[<<"silk/">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"safari">>},
                        {<<"name">>,<<"safari 6">>},
                        {<<"manufacturer">>,<<"apple">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"version/6">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"safari">>},
                        {<<"name">>,<<"safari 5">>},
                        {<<"manufacturer">>,<<"apple">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"version/5">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"safari">>},
                        {<<"name">>,<<"safari 4">>},
                        {<<"manufacturer">>,<<"apple">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"version/4">>]},
                        {<<"exclusions">>,[<<"linux">>,<<"googlebot-mobile">>]},
                        {<<"children">>,[]}]}]}]},
        {[{<<"family">>,<<"opera">>},
            {<<"name">>,<<"opera">>},
            {<<"manufacturer">>,<<"opera">>},
            {<<"browser_type">>,<<"web_browser">>},
            {<<"rendering_engine">>,<<"presto">>},
            {<<"version_regex">>,<<"opera\\/(([\\d]+)\\.([\\w]+))">>},
            {<<"aliases">>,[<<" opr/">>,<<"opera">>]},
            {<<"children">>,
                [{[{<<"family">>,<<"opera">>},
                    {<<"name">>,<<"opera mini">>},
                    {<<"manufacturer">>,<<"opera">>},
                    {<<"browser_type">>,<<"mobile_browser">>},
                    {<<"rendering_engine">>,<<"presto">>},
                    {<<"aliases">>,[<<"opera mini">>]},
                    {<<"children">>,[]}]},
                    {[{<<"family">>,<<"opera">>},
                        {<<"name">>,<<"opera 20">>},
                        {<<"manufacturer">>,<<"opera">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"version_regex">>,
                            <<"opr\\/(([\\d]+)\\.([\\w]+)?(\\.[\\w]+)?(\\.[\\w]+)?)">>},
                        {<<"aliases">>,[<<"opr/20.">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"opera">>},
                        {<<"name">>,<<"opera 19">>},
                        {<<"manufacturer">>,<<"opera">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"version_regex">>,
                            <<"opr\\/(([\\d]+)\\.([\\w]+)?(\\.[\\w]+)?(\\.[\\w]+)?)">>},
                        {<<"aliases">>,[<<"opr/19.">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"opera">>},
                        {<<"name">>,<<"opera 18">>},
                        {<<"manufacturer">>,<<"opera">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"version_regex">>,
                            <<"opr\\/(([\\d]+)\\.([\\w]+)?(\\.[\\w]+)?(\\.[\\w]+)?)">>},
                        {<<"aliases">>,[<<"opr/18.">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"opera">>},
                        {<<"name">>,<<"opera 17">>},
                        {<<"manufacturer">>,<<"opera">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"version_regex">>,
                            <<"opr\\/(([\\d]+)\\.([\\w]+)?(\\.[\\w]+)?(\\.[\\w]+)?)">>},
                        {<<"aliases">>,[<<"opr/17.">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"opera">>},
                        {<<"name">>,<<"opera 16">>},
                        {<<"manufacturer">>,<<"opera">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"version_regex">>,
                            <<"opr\\/(([\\d]+)\\.([\\w]+)?(\\.[\\w]+)?(\\.[\\w]+)?)">>},
                        {<<"aliases">>,[<<"opr/16.">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"opera">>},
                        {<<"name">>,<<"opera 15">>},
                        {<<"manufacturer">>,<<"opera">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"version_regex">>,
                            <<"opr\\/(([\\d]+)\\.([\\w]+)?(\\.[\\w]+)?(\\.[\\w]+)?)">>},
                        {<<"aliases">>,[<<"opr/15.">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"opera">>},
                        {<<"name">>,<<"opera 12">>},
                        {<<"manufacturer">>,<<"opera">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"presto">>},
                        {<<"version_regex">>,<<"version\\/(([\\d]+)\\.([\\w]+))">>},
                        {<<"aliases">>,[<<"opera/12">>,<<"version/12.">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"opera">>},
                        {<<"name">>,<<"opera 11">>},
                        {<<"manufacturer">>,<<"opera">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"presto">>},
                        {<<"version_regex">>,<<"version\\/(([\\d]+)\\.([\\w]+))">>},
                        {<<"aliases">>,[<<"version/11.">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"opera">>},
                        {<<"name">>,<<"opera 10">>},
                        {<<"manufacturer">>,<<"opera">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"presto">>},
                        {<<"version_regex">>,<<"version\\/(([\\d]+)\\.([\\w]+))">>},
                        {<<"aliases">>,[<<"opera/9.8">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"opera">>},
                        {<<"name">>,<<"opera 9">>},
                        {<<"manufacturer">>,<<"opera">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"presto">>},
                        {<<"aliases">>,[<<"opera/9">>]},
                        {<<"children">>,[]}]}]}]},
        {[{<<"family">>,<<"konqueror">>},
            {<<"name">>,<<"konqueror">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"web_browser">>},
            {<<"rendering_engine">>,<<"khtml">>},
            {<<"version_regex">>,<<"konqueror\\/(([0-9]+)\\.?([\\w]+)?(-[\\w]+)?)">>},
            {<<"aliases">>,[<<"konqueror">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"dolfin2">>},
            {<<"name">>,<<"samsung dolphin 2">>},
            {<<"manufacturer">>,<<"samsung">>},
            {<<"browser_type">>,<<"mobile_browser">>},
            {<<"rendering_engine">>,<<"webkit">>},
            {<<"aliases">>,[<<"dolfin/2">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"apple_web_kit">>},
            {<<"name">>,<<"apple webkit">>},
            {<<"manufacturer">>,<<"apple">>},
            {<<"browser_type">>,<<"web_browser">>},
            {<<"rendering_engine">>,<<"webkit">>},
            {<<"aliases">>,[<<"applewebkit">>]},
            {<<"exclusions">>,[<<"opr/">>,<<"web preview">>,<<"googlebot-mobile">>]},
            {<<"children">>,
                [{[{<<"family">>,<<"apple_web_kit">>},
                    {<<"name">>,<<"itunes">>},
                    {<<"manufacturer">>,<<"apple">>},
                    {<<"browser_type">>,<<"app">>},
                    {<<"rendering_engine">>,<<"webkit">>},
                    {<<"aliases">>,[<<"itunes">>]},
                    {<<"children">>,[]}]},
                    {[{<<"family">>,<<"apple_web_kit">>},
                        {<<"name">>,<<"app store">>},
                        {<<"manufacturer">>,<<"apple">>},
                        {<<"browser_type">>,<<"app">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"macappstore">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"apple_web_kit">>},
                        {<<"name">>,<<"adobe air application">>},
                        {<<"manufacturer">>,<<"adobe">>},
                        {<<"browser_type">>,<<"app">>},
                        {<<"rendering_engine">>,<<"webkit">>},
                        {<<"aliases">>,[<<"adobeair">>]},
                        {<<"children">>,[]}]}]}]},
        {[{<<"family">>,<<"lotus_notes">>},
            {<<"name">>,<<"lotus notes">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"email_client">>},
            {<<"rendering_engine">>,<<"other">>},
            {<<"version_regex">>,<<"lotus-notes\\/(([\\d]+)\\.([\\w]+))">>},
            {<<"aliases">>,[<<"lotus-notes">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"camino">>},
            {<<"name">>,<<"camino">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"web_browser">>},
            {<<"rendering_engine">>,<<"gecko">>},
            {<<"version_regex">>,<<"camino\\/(([0-9]+)\\.?([\\w]+)?(\\.[\\w]+)?)">>},
            {<<"aliases">>,[<<"camino">>]},
            {<<"children">>,
                [{[{<<"family">>,<<"camino">>},
                    {<<"name">>,<<"camino 2">>},
                    {<<"manufacturer">>,<<"other">>},
                    {<<"browser_type">>,<<"web_browser">>},
                    {<<"rendering_engine">>,<<"gecko">>},
                    {<<"aliases">>,[<<"camino/2">>]},
                    {<<"children">>,[]}]}]}]},
        {[{<<"family">>,<<"flock">>},
            {<<"name">>,<<"flock">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"web_browser">>},
            {<<"rendering_engine">>,<<"gecko">>},
            {<<"version_regex">>,<<"flock\\/(([0-9]+)\\.?([\\w]+)?(\\.[\\w]+)?)">>},
            {<<"aliases">>,[<<"flock">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"firefox">>},
            {<<"name">>,<<"firefox">>},
            {<<"manufacturer">>,<<"mozilla">>},
            {<<"browser_type">>,<<"web_browser">>},
            {<<"rendering_engine">>,<<"gecko">>},
            {<<"version_regex">>,
                <<"firefox/(([0-9]+)(?:\\.([0-9]+))?(?:[ab\\.]([0-9]+))?(?:[ab\\.]([0-9]+))?)">>},
            {<<"aliases">>,[<<"firefox">>]},
            {<<"exclusions">>,[<<"ggpht.com">>]},
            {<<"children">>,
                [{[{<<"family">>,<<"firefox">>},
                    {<<"name">>,<<"firefox 3 mobile">>},
                    {<<"manufacturer">>,<<"mozilla">>},
                    {<<"browser_type">>,<<"mobile_browser">>},
                    {<<"rendering_engine">>,<<"gecko">>},
                    {<<"aliases">>,[<<"firefox/3.5 maemo">>]},
                    {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox mobile">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"mobile_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"mobile">>]},
                        {<<"children">>,
                            [{[{<<"family">>,<<"firefox">>},
                                {<<"name">>,<<"firefox mobile 23">>},
                                {<<"manufacturer">>,<<"mozilla">>},
                                {<<"browser_type">>,<<"mobile_browser">>},
                                {<<"rendering_engine">>,<<"gecko">>},
                                {<<"aliases">>,[<<"firefox/23">>]},
                                {<<"children">>,[]}]}]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 30">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/30">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 29">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/29">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 28">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/28">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 27">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/27">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 26">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/26">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 25">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/25">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 24">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/24">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 23">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/23">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 22">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/22">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 21">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/21">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 20">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/20">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 19">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/19">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 18">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/18">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 17">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/17">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 16">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/16">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 15">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/15">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 14">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/14">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 13">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/13">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 12">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/12">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 11">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/11">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 10">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/10">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 9">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/9">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 8">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/8">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 7">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/7">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 6">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/6">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 5">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/5">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 4">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/4">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 3">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/3">>]},
                        {<<"exclusions">>,[<<"ggpht.com">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 2">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/2">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"firefox">>},
                        {<<"name">>,<<"firefox 1.5">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"web_browser">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"firefox/1.5">>]},
                        {<<"children">>,[]}]}]}]},
        {[{<<"family">>,<<"thunderbird">>},
            {<<"name">>,<<"thunderbird">>},
            {<<"manufacturer">>,<<"mozilla">>},
            {<<"browser_type">>,<<"email_client">>},
            {<<"rendering_engine">>,<<"gecko">>},
            {<<"version_regex">>,
                <<"thunderbird\\/(([0-9]+)\\.?([\\w]+)?(\\.[\\w]+)?(\\.[\\w]+)?)">>},
            {<<"aliases">>,[<<"thunderbird">>]},
            {<<"children">>,
                [{[{<<"family">>,<<"thunderbird">>},
                    {<<"name">>,<<"thunderbird 12">>},
                    {<<"manufacturer">>,<<"mozilla">>},
                    {<<"browser_type">>,<<"email_client">>},
                    {<<"rendering_engine">>,<<"gecko">>},
                    {<<"aliases">>,[<<"thunderbird/12">>]},
                    {<<"children">>,[]}]},
                    {[{<<"family">>,<<"thunderbird">>},
                        {<<"name">>,<<"thunderbird 11">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"email_client">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"thunderbird/11">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"thunderbird">>},
                        {<<"name">>,<<"thunderbird 10">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"email_client">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"thunderbird/10">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"thunderbird">>},
                        {<<"name">>,<<"thunderbird 8">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"email_client">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"thunderbird/8">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"thunderbird">>},
                        {<<"name">>,<<"thunderbird 7">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"email_client">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"thunderbird/7">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"thunderbird">>},
                        {<<"name">>,<<"thunderbird 6">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"email_client">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"thunderbird/6">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"thunderbird">>},
                        {<<"name">>,<<"thunderbird 3">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"email_client">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"thunderbird/3">>]},
                        {<<"children">>,[]}]},
                    {[{<<"family">>,<<"thunderbird">>},
                        {<<"name">>,<<"thunderbird 2">>},
                        {<<"manufacturer">>,<<"mozilla">>},
                        {<<"browser_type">>,<<"email_client">>},
                        {<<"rendering_engine">>,<<"gecko">>},
                        {<<"aliases">>,[<<"thunderbird/2">>]},
                        {<<"children">>,[]}]}]}]},
        {[{<<"family">>,<<"seamonkey">>},
            {<<"name">>,<<"seamonkey">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"web_browser">>},
            {<<"rendering_engine">>,<<"gecko">>},
            {<<"version_regex">>,<<"seamonkey\\/(([0-9]+)\\.?([\\w]+)?(\\.[\\w]+)?)">>},
            {<<"aliases">>,[<<"seamonkey">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"bot">>},
            {<<"name">>,<<"robot/spider">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"robot">>},
            {<<"rendering_engine">>,<<"other">>},
            {<<"aliases">>,
                [<<"googlebot">>,<<"web preview">>,<<"bot">>,<<"spider">>,<<"crawler">>,
                    <<"feedfetcher">>,<<"slurp">>,<<"twiceler">>,<<"nutch">>,
                    <<"becomebot">>]},
            {<<"children">>,
                [{[{<<"family">>,<<"bot">>},
                    {<<"name">>,<<"mobil robot/spider">>},
                    {<<"manufacturer">>,<<"other">>},
                    {<<"browser_type">>,<<"robot">>},
                    {<<"rendering_engine">>,<<"other">>},
                    {<<"aliases">>,[<<"googlebot-mobile">>]},
                    {<<"children">>,[]}]}]}]},
        {[{<<"family">>,<<"mozilla">>},
            {<<"name">>,<<"mozilla">>},
            {<<"manufacturer">>,<<"mozilla">>},
            {<<"browser_type">>,<<"web_browser">>},
            {<<"rendering_engine">>,<<"other">>},
            {<<"aliases">>,[<<"mozilla">>,<<"moozilla">>]},
            {<<"exclusions">>,[<<"ggpht.com">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"cfnetwork">>},
            {<<"name">>,<<"cfnetwork">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"unknown">>},
            {<<"rendering_engine">>,<<"other">>},
            {<<"aliases">>,[<<"cfnetwork">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"eudora">>},
            {<<"name">>,<<"eudora">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"email_client">>},
            {<<"rendering_engine">>,<<"other">>},
            {<<"aliases">>,[<<"eudora">>,<<"eudora">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"pocomail">>},
            {<<"name">>,<<"pocomail">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"email_client">>},
            {<<"rendering_engine">>,<<"other">>},
            {<<"aliases">>,[<<"pocomail">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"thebat">>},
            {<<"name">>,<<"the bat!">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"email_client">>},
            {<<"rendering_engine">>,<<"other">>},
            {<<"aliases">>,[<<"the bat">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"netfront">>},
            {<<"name">>,<<"netfront">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"mobile_browser">>},
            {<<"rendering_engine">>,<<"other">>},
            {<<"aliases">>,[<<"netfront">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"evolution">>},
            {<<"name">>,<<"evolution">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"email_client">>},
            {<<"rendering_engine">>,<<"other">>},
            {<<"aliases">>,[<<"camelhttpstream">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"lynx">>},
            {<<"name">>,<<"lynx">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"text_browser">>},
            {<<"rendering_engine">>,<<"other">>},
            {<<"version_regex">>,
                <<"lynx\\/(([0-9]+)\\.([\\d]+)\\.?([\\w-+]+)?\\.?([\\w-+]+)?)">>},
            {<<"aliases">>,[<<"lynx">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"download">>},
            {<<"name">>,<<"downloading tool">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"tool">>},
            {<<"rendering_engine">>,<<"other">>},
            {<<"aliases">>,
                [<<"curl">>,<<"wget">>,<<"ggpht.com">>,<<"apache-httpclient">>]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"unknown">>},
            {<<"name">>,<<"unknown">>},
            {<<"manufacturer">>,<<"other">>},
            {<<"browser_type">>,<<"unknown">>},
            {<<"rendering_engine">>,<<"other">>},
            {<<"aliases">>,[]},
            {<<"children">>,[]}]},
        {[{<<"family">>,<<"apple_mail">>},
            {<<"name">>,<<"apple mail">>},
            {<<"manufacturer">>,<<"apple">>},
            {<<"browser_type">>,<<"email_client">>},
            {<<"rendering_engine">>,<<"webkit">>},
            {<<"aliases">>,[]},
            {<<"children">>,[]}]}].